"""sensPy - Python port of sensR."""

from .links import psyfun, psyinv, psyderiv, rescale
from .models import BetaBinomial
from .discrimination import (
    two_afc,
    duotrio_pc,
    three_afc_pc,
    triangle_pc,
    tetrad_pc,
    hexad_pc,
    twofive_pc,
    get_pguess,
    pc2pd,
    pd2pc,
    discrim_2afc,
    "discrim",
    "twoAC",
    "dod",
    "samediff",
    "dprime_test",
    "dprime_compare",
    "SDT",
    "AUC",
    "par2prob_dod", 
    "dod_nll",      
    "samediff_nll", 
)
from .power import beta_binomial_power, find_critical_binomial_value, exact_binomial_power, sample_size_for_binomial_power, power_discrim
from .plotting import plot_psychometric
from .utils import has_jax, version

__all__ = [
    "psyfun",
    "psyinv",
    "psyderiv",
    "rescale",
    "BetaBinomial",
    "two_afc",
    "duotrio_pc",
    "three_afc_pc",
    "triangle_pc",
    "tetrad_pc",
    "hexad_pc",
    "twofive_pc",
    "get_pguess",
    "pc2pd",
    "pd2pc",
    "discrim_2afc",
    "discrim",
    "twoAC",
    "dod",
    "samediff",
    "dprime_test",
    "dprime_compare",
    "SDT",
    "AUC",
    "par2prob_dod",
    "dod_nll",
    "samediff_nll",
    "beta_binomial_power",
    "find_critical_binomial_value",
    "exact_binomial_power",
    "sample_size_for_binomial_power",
    "power_discrim",
    "plot_psychometric",
    "has_jax",
    "version",
]
